# This is a basic workflow to help you get started with Actions

name: "Sharing Session"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: sharing-session

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Whoami
        run: |
          whoami
          pwd

      - name: List files or Directory
        run: |
          ls -alth .

      - name: Get Branch Name
        run: echo "Branch name is ${GITHUB_REF#refs/heads/}"

      - name: Get Source and Target Branches (Pull Request)
        run: |
          echo "Source: ${{ github.head_ref }}, Target: ${{ github.base_ref }}"

      - name: Set Branch Name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Use Branch Name
        run: echo "Branch is $BRANCH_NAME"
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
